src/accounts/urls.py
from django.urls import path

from accounts.views import AccountRegistrationView, AccountLoginView, AccountLogoutView, AccountUpdateView, \
    UserPasswordChangeView, ContactUsView

app_name = 'accounts'

urlpatterns = [

    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('password/', UserPasswordChangeView.as_view(), name='password'),
    path('contact_us/', ContactUsView.as_view(), name='contact_us'),

]

src/app/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView


API_PREFIX = 'api/v1'


urlpatterns = [

    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name='index.html'), name='index'),

    path('accounts/', include('accounts.urls')),

    path('quizes/', include('quiz.urls')),

    path('__debug__/', include(debug_toolbar.urls)),

    path(f'{API_PREFIX}/', include('quiz.api.urls')),
    path(f'{API_PREFIX}/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(f'{API_PREFIX}/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = 'quiz.views.error_400'
handler403 = 'quiz.views.error_403'
handler404 = 'quiz.views.error_404'
handler500 = 'quiz.views.error_500'

src/accounts/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    image = models.ImageField(null=True, default='default.jpg', upload_to='pics/')
    rating = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])

    email_sent = models.DateTimeField(null=True, auto_now=True)
    motivation_count = models.IntegerField(default=0, blank=True)

    def save(self, *args, **kwargs):
        self.rating = min(100, self.rating)
        self.full_clean()
        super().save(*args, **kwargs)

src/quiz/models.py
import datetime

from django.db import models
from django.core.validators import MaxValueValidator

from accounts.models import User

# Create your models here.
from core.models import BaseModel
from core.utils import generate_uuid


class Test(BaseModel):
    QUESTION_MIN_LIMIT = 3
    QUESTION_MAX_LIMIT = 20

    class LEVEL_CHOICES(models.IntegerChoices):
        BASIC = 0, "Basic"
        MIDDLE = 1, "Middle"
        ADVANCED = 2, "Advanced"

    # topic = models.ForeignKey(to=Topic, related_name='tests', null=True, on_delete=models.SET_NULL)
    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)
    title = models.CharField(max_length=64)
    description = models.TextField(max_length=1024, null=True, blank=True)
    level = models.PositiveSmallIntegerField(choices=LEVEL_CHOICES.choices, default=LEVEL_CHOICES.MIDDLE)
    image = models.ImageField(default='default.png', upload_to='covers')

    def questions_count(self):
        return self.questions.count()

    def last_run(self):
        return self.results.last().create_date

    def get_best_result(self):
        return self.results.order_by('-num_correct_answers').first().num_correct_answers

    def get_best_user(self):
        result = self.results.extra(
            select={'time_spent': 'write_date - create_date'},
            order_by=['-num_correct_answers', 'time_spent']).first().user
        return result

    def __str__(self):
        return f'{self.title}'


class Question(models.Model):
    ANSWER_MIN_LIMIT = 3
    ANSWER_MAX_LIMIT = 6

    test = models.ForeignKey(to=Test, related_name='questions', on_delete=models.CASCADE)
    order_number = models.PositiveSmallIntegerField(
        validators=[MaxValueValidator(Test.QUESTION_MAX_LIMIT)]
    )
    text = models.CharField(max_length=64)

    def __str__(self):
        return f'{self.text}'


class Choice(models.Model):
    text = models.CharField(max_length=64)
    question = models.ForeignKey(to=Question, related_name='choices', on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.text}'


class Result(BaseModel):
    class STATE(models.IntegerChoices):
        NEW = 0, "New"
        FINISHED = 1, "Finished"

    user = models.ForeignKey(to=User, related_name='results', on_delete=models.CASCADE)
    test = models.ForeignKey(to=Test, related_name='results', on_delete=models.CASCADE)
    state = models.PositiveSmallIntegerField(default=STATE.NEW, choices=STATE.choices)
    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)
    current_order_number = models.PositiveSmallIntegerField(null=True)

    num_correct_answers = models.PositiveSmallIntegerField(
        default=0,
        validators=[
            MaxValueValidator(Test.QUESTION_MAX_LIMIT)
        ]
    )
    num_incorrect_answers = models.PositiveSmallIntegerField(
        default=0,
        validators=[
            MaxValueValidator(Test.QUESTION_MAX_LIMIT)
        ]
    )

    def update_result(self, order_number, question, selected_choices):
        correct_choices = [
            choice.is_correct
            for choice in question.choices.all()
        ]

        correct_answer = True
        for x, y in zip(correct_choices, selected_choices):
            correct_answer &= (x == y)

        self.num_correct_answers += int(correct_answer)
        self.num_incorrect_answers += 1 - int(correct_answer)
        self.current_order_number = order_number
        if order_number == question.test.questions_count():
            self.state = self.STATE.FINISHED
            self.user.rating += self.points()
            self.user.save()
        self.save()

    def time_spent(self):
        time_spent = self.write_date - self.create_date
        return time_spent - datetime.timedelta(microseconds=time_spent.microseconds)

    def points(self):
        return max(0, self.num_correct_answers - self.num_incorrect_answers)

    def score(self):
        return f'{round((self.num_correct_answers / self.test.questions_count()) * 100, 2)} %'

src/accounts/forms.py
from PIL import Image # noqa

from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm, Form, fields

from accounts.models import User

from django import forms


class AccountRegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


class AccountUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'bio', 'birth_date']

    # def save(self, commit=True):
    #     super().save(commit)
    #     image = Image.open(self.instance.image)
    #     image.thumbnail((300, 300), Image.ANTIALIAS)
    #     image.save(self.instance.image.path)


class ContactUs(Form):
    subject = fields.CharField(max_length=256, empty_value='Message from Quiz')
    message = fields.CharField(widget=forms.Textarea)

src/accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.core.mail import send_mail
from django.shortcuts import render # noqa
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView
from django.views.generic.edit import UpdateView, FormView

from accounts.forms import AccountRegistrationForm, AccountUpdateForm, ContactUs
from accounts.models import User
# Create your views here.


class AccountRegistrationView(CreateView):
    model = User
    template_name = 'registration.html'
    success_url = reverse_lazy('accounts:login')
    form_class = AccountRegistrationForm

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, 'User successfully registered')
        return result


class AccountLoginView(LoginView):
    success_url = reverse_lazy('index')
    template_name = 'login.html'

    def get_redirect_url(self):
        if self.request.GET.get('next'):
            return self.request.GET.get('next')
        return reverse('index')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, f'User {self.request.user} successfully logged in')
        return result


class AccountLogoutView(LogoutView):
    template_name = 'logout.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.info(self.request, f'User {self.request.user} has been logged out')
        return super().dispatch(request, *args, **kwargs)


class AccountUpdateView(UpdateView):
    model = User
    template_name = 'profile.html'
    success_url = reverse_lazy('index')
    form_class = AccountUpdateForm
    paginate_by = 5

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(object_list=self.get_queryset(), **kwargs)
        return context

    def get_queryset(self):
        return self.object.results.all().select_related('test')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, 'Profile successfully updated')
        return result


class UserPasswordChangeView(PasswordChangeView):
    model = User
    success_url = reverse_lazy('accounts:profile')
    template_name = 'password-change.html'


class ContactUsView(LoginRequiredMixin, FormView):
    template_name = 'contact_us.html'
    success_url = reverse_lazy('index')
    form_class = ContactUs

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            send_mail(
                subject=form.cleaned_data['subject'],
                message=form.cleaned_data['message'],
                from_email=request.user.email,
                recipient_list=settings.EMAIL_HOST_RECIPIENT.split(':'),
                fail_silently=False,
            )
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

src/accounts/templates/contact_us.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block operation %}
    <h1><font size="60px" color="#ffa600"  face="Calibri">Contact Us</font></h1>
{% endblock %}


{% block main %}
    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <div class="mt-3">
            <input class="btn btn-success" type="submit" value="Send a message">
            <a class="btn btn-light" href="{% url 'index' %}">Home</a>
        </div>
    </form>
{% endblock %}

src/accounts/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block operation%}
    <h1><font size="60px" color="#ffa600"  face="Calibri">Login as user</font> </h1>
{% endblock %}


{% block main %}
    <form method='post'>
      {% csrf_token %}
      {{form|crispy}}

      <input class="btn btn-secondary" type="submit" value="Login">
    </form>
{% endblock %}

src/accounts/templates/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block operation%}
   <div style="text-align: center">
      <a href="{% url 'index' %}"  class="btn btn-info" style="font-size: 25px">Home</a>
   </div>
{% endblock %}


{% block main %}
{% endblock %}

src/accounts/templates/password-change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block operation%}
    <h1><font size="60px" color="#ffa600"  face="Calibri">Change password</font> </h1>
{% endblock %}


{% block main %}
    <form method='post'>
      {% csrf_token %}
      {{form|crispy}}

      <input class="btn btn-success" type="submit" value="Change">
    </form>
{% endblock %}

src/accounts/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block operation%}
    <h1><font size="60px" color="#ffa600"  face="Calibri">Account update</font> </h1>
{% endblock %}


{% block main %}
    <div>
        <form method='post'>
          {% csrf_token %}
          {{form|crispy}}

        <div style="text-align: center; font-size: 33px; font-family: Arial">TEST RESULTS:</div>
                <br>
                <table class="table table-striped table-hover">
                      <tr>
                        <th>#</th>
                        <th>Test</th>
                        <th>Create date</th>
                        <th>Write date</th>
                        <th>Points</th>
                        <th>State</th>
                      </tr>
                            {% for result in object_list %}
                                  <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ result.test }}</td>
                                    <td>{{ result.create_date }}</td>
                                    <td>{{ result.write_date }}</td>
                                    <td>{{ result.points }}</td>
                                    <td>{{ result.get_state_display }}</td>
                                  </tr>
                            {% endfor %}
                </table>
            <div style="text-align: center; font-size: 33px; font-family: Arial">TOTAL SCORE: {{ user.rating }}</div>
            <br>

          <input class="btn btn-success" type="submit" value="Save">
          <a href="{% url 'accounts:password' %}" class="btn btn-info">Change password</a>
        </form>
    </div>
{% endblock %}

src/accounts/templates/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block operation%}
    <h1><font size="60px" color="#ffa600"  face="Calibri">Account creation</font> </h1>
{% endblock %}


{% block main %}
    <form method='post'>
      {% csrf_token %}
      {{form|crispy}}

      <input class="btn btn-secondary" type="submit" value="Create">
    </form>
{% endblock %}